### ISSUE TITLE
Add anti-affinity config

### ISSUE THREAD

**Issue by efinlay24** [Financial-Times/concepts-rw-neo4j#24]
Example:
https://github.com/Financial-Times/aggregate-concept-transformer/pull/15/files#diff-2fb12849c83958405281e710236671dc

---

https://trello.com/c/9LCirfjQ/154-add-anti-affinity-config-for-k8s-only-services-like-the-pub-varnishes-and-any-other-service-without-this

**Comment by tamas-molnar** [comment]
Done in https://github.com/Financial-Times/concepts-rw-neo4j/pull/21
